[package]
name = "mame_software_lists"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xml-rs = "0.8.3"
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.5"